// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/home/victor93/CmExperimentFolder/2026_Pu239/2026_Pu239/Plots01_Victor/./Plot2DHisto.cc";

#endif
